### ISSUE TITLE
Support VSIX template as well as dotnet new

### ISSUE THREAD

**Issue by alhardy** [prospa-group-oss/DotnetTemplates#4]

**Comment by avishnyakov** [comment]
@alhardy do we still write VSIX for VS2017? I did some for VS2013, 2015 but never looked into migrating to VS2017.

Here is my work for the reference:
> https://github.com/SubPointSolutions/spmeta2-vsixextensions

**Comment by alhardy** [comment]
Thanks @avishnyakov, as we discussed not worth the effort to write a vsix so closing this one
